server:
  port: 8881

spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      name: config-client #配置中心文件名，当没有配置spring.cloud.config.name时，默认spring.application.name为文件名
      profile: dev
      #uri: http://localhost:8888/  #配置中心改为集群后，此处注掉
      discovery:
        enabled: true #配置中心改为集群后,加上
        service-id: config-server #配置中心改为集群后,加上
    #消息总线
    bus:
      enabled: true
      trace:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#服务监控
management:
  endpoints:
    web:
      exposure.include: bus-refresh




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/