server:
    port: 8888

spring:
    application:
        name: config-server
    cloud:
        config:
            #配置仓库的分支
            label: master
            server:
                git:
                    #配置仓库路径
                    searchPaths: cloud
                    #配置git仓库地址
                    uri: https://gitee.com/ntcjq/spring-cloud-config.git
                    username: ''
                    password: ''

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/